[project]
name = "pcs"
version = "1.2.0"
description = "Purge Controller Service - a service to commission file deletions"
dependencies = [
    "ghga-service-commons[api]>=3.0.0",
    "ghga-event-schemas==3.0.0",
    "hexkit[akafka]>=2.1.0",
    "typer>=0.9.0",
]

[project.urls]
Repository = "https://github.com/ghga-de/pcs"

[project.scripts]
pcs = "pcs.__main__:cli"
